# Generated by Django 4.1.7 on 2023-11-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Test", "0002_remove_test_testid"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="matLength",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="test",
            name="matWidth",
            field=models.FloatField(default=0.0),
        ),
    ]
