# Generated by Django 4.2.7 on 2023-11-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matWidth', models.FloatField()),
                ('matLength', models.FloatField()),
            ],
        ),
    ]
