# Generated by Django 4.1.7 on 2023-11-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Test", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="testID",
        ),
    ]
